### ISSUE TITLE
Cannot find the repository rmf 

### ISSUE THREAD

**Issue by duy12i1i7** [ntnu-arl/ORACLE#1]
Hello guys!
I'm student, trying to test this project. But when i try to rerun flightmare enviroment for seVAE, i am failed when i run '''vcs-import < agile_autonomy/dependencies.yaml'''.
I look on logs and realize that '''https://github.com/ntnu-arl/rmf_sim.git''' is not available. It means that is maybe removed.
How can I fix that?
Thanks alot

**Comment by HuanNguyenARL** [comment]
Please try to run the command `vcs-import < agile_autonomy/dependencies.yaml` again (in the branch oracle_integrate of agile_autonomy repo). We have updated the link of rmf_sim to our public repo.

**Comment by duy12i1i7** [comment]
Thanks for your supports. But please ensure that rmf_sim was published. I tried to run this command `vcs-import < agile_autonomy/dependencies.yaml` but I got this error on my terminal: 
![Screenshot from 2023-12-27 20-49-39](https://github.com/ntnu-arl/ORACLE/assets/130693469/e15b7e42-4914-4c03-bf59-5f35f3261e9b)
I checked by web browser (Firefox), and the result is like this:
![Screenshot from 2023-12-27 20-55-42](https://github.com/ntnu-arl/ORACLE/assets/130693469/04d06d41-96aa-4514-826d-a390b46ac09f)

Plz help me to fix this problem. Thanks alot

**Comment by duy12i1i7** [comment]
Oh I just see the change on your repo. Sorry for my mistake. But now it is overtime, I will check soon. Thanks alot

**Comment by duy12i1i7** [comment]
Sorry for my delay. Today, I had test your changes on your repository. But I got this error when I ran `catkin build`, How can I fix that?
 Thanks alot
![Screenshot from 2023-12-30 21-15-17](https://github.com/ntnu-arl/ORACLE/assets/130693469/a97eaa51-fa04-4ae5-9b51-b7181e25d884)

**Comment by HuanNguyenARL** [comment]
Hi, you will need to install Open3D v0.9.0 to build the agile_autonomy workspace. This is mentioned here: https://github.com/uzh-rpg/agile_autonomy/issues/66. Hope that helps.

**Comment by HuanNguyenARL** [comment]
Hi @duy12i1i7, if there are no more questions, can you please close this issue?

**Comment by duy12i1i7** [comment]
okie, thanks so much
