### ISSUE TITLE
Some errors related to Flightmare Environment make drone can not fly.

### ISSUE THREAD

**Issue by duy12i1i7** [ntnu-arl/ORACLE#3]
Hello guys!! I'm here
I'm a student, trying to test this project. But when I tried to rerun flightmare environment for seVAE, I got some problems with simulator 4 on your's wiki. Maybe the problem appeared when I call 
`rosservice call /start_planner "{}"`
Here is thie picture about this bug
![Screenshot from 2024-03-06 13-17-49](https://github.com/ntnu-arl/ORACLE/assets/130693469/a18682e8-9ab9-4d82-a4c4-0e713e55e232)

On the first and second terminal, I feel no bug on this

![Screenshot from 2024-03-06 13-26-48](https://github.com/ntnu-arl/ORACLE/assets/130693469/2a70f149-87bb-42e1-a129-ef866ca5ca1c)
-
![Screenshot from 2024-03-06 13-27-25](https://github.com/ntnu-arl/ORACLE/assets/130693469/59e699ed-03d2-4958-a973-432d742fd8dd)

But when I tried to run `python evaluate/evaluate.py` on the third terminal, I feel everything to be OK, but I can't see the green text `START planner` printed out. It stop like this

![Screenshot from 2024-03-06 13-29-35](https://github.com/ntnu-arl/ORACLE/assets/130693469/215395b9-78c6-46ae-b806-03f9a600e460)

Afterthat, I called `rosservice call /start_planner "{}"` on fourth terminal, I have errors like that:

![Screenshot from 2024-03-06 13-31-17](https://github.com/ntnu-arl/ORACLE/assets/130693469/a22369c6-05a6-4eaa-aefa-566efc5147ca)
-
![Screenshot from 2024-03-06 13-31-21](https://github.com/ntnu-arl/ORACLE/assets/130693469/885e454c-2521-4430-b449-f65ca8bceac4)
-
![Screenshot from 2024-03-06 13-31-30](https://github.com/ntnu-arl/ORACLE/assets/130693469/69c67d0f-db5e-4232-8095-3eb130be614a)
-
![Screenshot from 2024-03-06 13-31-36](https://github.com/ntnu-arl/ORACLE/assets/130693469/bb836254-bc3c-412c-9e96-2d625ef6da70)

And Everything stoped when I called `rosservice call /start_planner "{}"`

So how can I fix that?
Thanks alot

**Comment by duy12i1i7** [comment]
I found that This bug maybe related to config `EXPERT_FOLDER` when `agile_autonomy/data_generation/data/` do not exist on agile directory, so How can I fix that?

**Comment by HuanNguyenARL** [comment]
Hi @duy12i1i7, you can manually create the folder by yourself.

**Comment by duy12i1i7** [comment]
oh I see. I fixed this. Thanks alot!!!
