### ISSUE TITLE
Some questions related to Flightmare Environment

### ISSUE THREAD

**Issue by duy12i1i7** [ntnu-arl/ORACLE#4]
Hello guys!! I'm here
I'm a student trying to test this project. After all the bugs, I finally ran this project-related seVAE and demo on the Flightmare environment. However, I have some questions about the process I am trying to test this project.
Firstly, when I enabled all of the functions to visual images(at the `simulation_oracle.launch` file), I saw that it has 2 screens that display RGB images. It may be from the same environment, but it doesn't have the same angle of view. 
Is this issue arising because of an incorrect configuration on my part, or is it an inherent feature of the application?

![Screenshot from 2024-03-13 19-14-51](https://github.com/ntnu-arl/ORACLE/assets/130693469/94c08330-b5e5-418d-ad67-7947f3b0b48d)

Another question is that when I try to test your AI model, everything is OK when I try to test Demo 1 and 2. But when I try to test Demo 4, every time I try, the drone is always colliding, and it has the same parameter when it collides. Is this issue arising because of an incorrect configuration on my part, or is it an inherent feature of the application?

![Screenshot from 2024-03-13 19-15-10](https://github.com/ntnu-arl/ORACLE/assets/130693469/e992a02d-d2b9-427f-a96b-d5f7f4b9cdac)

Thanks a lot!!!

**Comment by HuanNguyenARL** [comment]
Hi @duy12i1i7, 
1) The viewing angle of the window rpg_flightmare is not the same as the onboard camera. This is the inherent feature of the original [agile_autonomy](https://github.com/uzh-rpg/agile_autonomy) repo. We modified the original repo to suit our needs.
2) For the demo 4, you can reduce this [threshold  ](https://github.com/ntnu-arl/ORACLE/blob/d7888de138bc901d57df52835b20b2951a6a76bb/config_files/config_flightmare_sevae_oracle.py#L86) a bit (for example COLLISION_THRESHOLD = 0.01-0.08). Additionally, you can increase [the gain of the yaw controller](https://github.com/ntnu-arl/lmf_gazebo_models/blob/dd31ff13495e9f5548f5cbf7dd00235a6a82233f/rmf_sim/rotors/pid_position_delta.yaml#L36) (for example K_yaw=2.2-2.4) to make the drone track the command better. You can verify the result of the network prediction by looking at the markers in rviz. 
Empirically, we found that the current weights of ORACLE (Demo 3) can perform better than the current weights of seVAE-ORACLE (Demo 4) in Flightmare. It is noted that these 2 networks are not fine-tuned at all in Flightmare.

**Comment by duy12i1i7** [comment]
Hi @HuanNguyenARL,
Thanks a lot for your answer. I'd like to ask you one more question about the Fightmare environment, I am eager to learn how to create a similar realistic simulation environment based on Flightmare. I just found and did it based on the `flightmare_unity` repo; however, this is unsuitable for your project.

**Comment by HuanNguyenARL** [comment]
Hi @duy12i1i7, thank you for your interest in our work. To use Flightmare with our work, I can see 2 ways:
- You can collect data with it to train the seVAE if you're using seVAE-ORACLE.
- The roll-out to collect data to train the CPN can be more involved but feasible since the collision label is available in Flightmare + the physics utilized by Flightmare is still RotorS.
