### ISSUE TITLE
ardupilot real-time ros wrapper

### ISSUE THREAD

**Issue by guglielmo610** [ntnu-arl/ORACLE#5]
Hello,
Do you have a version of the file "realtime_ros_wrapper_infogain_ardupilot.py" that can be used to fly with sevae-ORACLE? Because in this file is not consider at all the latent space that should be generated from the autoencoder.
Thank you.

**Comment by HuanNguyenARL** [comment]
Sorry for the late reply, you could make a subscriber for the latent vector in "realtime_ros_wrapper_infogain_ardupilot.py" like this:
[sevae_realtime_ros_wrapper_infogain_ardupilot.zip](https://github.com/ntnu-arl/ORACLE/files/15374457/sevae_realtime_ros_wrapper_infogain_ardupilot.zip)

**Comment by guglielmo610** [comment]
Thank you for the support!
